### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by fireboy637** [XiaoYuOvO/FishModLoader#2]
[latest.log](https://github.com/user-attachments/files/16522046/latest.log)

**Comment by fireboy637** [comment]
就有问题在它没有crash_report，直接嘎了
我是手动安装

**Comment by fireboy637** [comment]
> 日志里没什么有用的信息,发crash report

以下是HMCL中有，日志里没有的
Exception in thread "main" java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.xiaoyu233.fml.classloading.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:432)
	at net.xiaoyu233.fml.classloading.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:331)
	at net.xiaoyu233.fml.classloading.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.xiaoyu233.fml.classloading.KnotClassLoader.loadClass(KnotClassLoader.java:104)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.xiaoyu233.fml.relaunch.Launch.launch(Launch.java:74)
	at net.xiaoyu233.fml.relaunch.LaunchDelegate.delegateLaunch(LaunchDelegate.java:50)
	at net.xiaoyu233.fml.relaunch.client.Main.main(Main.java:12)
Caused by: java.lang.NoSuchMethodError: 'void com.google.common.io.Closeables.closeQuietly(java.io.Reader)'
	at org.spongepowered.asm.mixin.refmap.ReferenceMapper.read(ReferenceMapper.java:274)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:630)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:504)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:407)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:222)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:227)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:195)
	at net.xiaoyu233.fml.classloading.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	... 7 more
[HMCL ProcessListener] Minecraft exit with code 1(0x1), type is APPLICATION_ERROR.

**Comment by ysesiq** [comment]
你加我qq,我给你现成的客户端吧

**Comment by ysesiq** [comment]
2146174683
