### ISSUE TITLE
Unsupported Class file?

### ISSUE THREAD

**Issue by KuraakaiGoro** [XiaoYuOvO/FishModLoader#3]
Exception caught from launcher
java.lang.UnsupportedClassVersionError: net/xiaoyu233/fml/relaunch/client/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:88)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:104)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Process exited with code 2.

**Comment by ysesiq** [comment]
use java17

**Comment by ghost** [comment]
I've tried Java17, but even with check compatibility turned off, it wouldn't work

**Comment by ysesiq** [comment]
Please send a crash message when using java17

**Comment by ghost** [comment]
Weird enough, I tried it one day and it just worked. Maybe it needed a restart
